# Initial Setup

In [39]:
from selenium import webdriver
import pandas as pd
import numpy as np
import glob
import os
from datetime import datetime
import time
import multiprocessing
# import threading

In [2]:
driver = webdriver.Chrome(r"C:\Users\yhfdidi\Documents\Python Scripts\Chrome-Driver\chromedriver_win32_ver87\chromedriver.exe")

In [3]:
url = "https://screener.fidelity.com/ftgw/etf/gotoCL/snapshot/advancedChart.jhtml?symbols=NIO"
driver.get(url)

In [152]:
handles = driver.window_handles
driver.switch_to.window(handles[0])

In [79]:
# driver.find_element_by_xpath("//input[@name = 'symbol']").click()
# driver.find_element_by_xpath("//input[@name = 'symbol']").clear()
# driver.find_element_by_xpath("//input[@name = 'symbol']").send_keys('NIO')
# driver.find_element_by_xpath("//input[@value = 'Go']").click()

In [80]:
# driver.find_element_by_xpath("//span[@class=\"export-menu-triangle\"]").click()
# driver.find_element_by_xpath("//div[@ng-click=\"clickExportSpreadsheet()\"]/..").click()

In [88]:
# list_of_files = glob.glob(r"C:\Users\yhfdidi\Downloads\GChromeDownloads\*.csv") # * means all if need specific format then *.csv
# latest_file = max(list_of_files, key=os.path.getctime)
# print(latest_file)

# df = pd.read_csv(latest_file)
# # filt = [not pd.isnull(x) for x in df['Open']]
# # df[filt]
# datestr = str(datetime.now()).split()[0].replace('-', '/')
# datestr = datestr[5:] + '/' + datestr[:4]
# df_need = df[df['Date'] == datestr]
# df_need['Close'] < df_need['BBUpper']
# df_need

C:\Users\yhfdidi\Downloads\GChromeDownloads\Chart-20201123-220453.csv

,Date,Open,High,Low,Close,Volume,BBUpper,BBLower,SMA(10),SMA(20),SMA(60)
502,11/23/2020,50.86,55.7,50.48,55.38,270203004.0,55.945522,26.139478,46.78,41.0425,27.938167

# Stock Analysis Module

In [ ]:
def run_main():
    while True:
            print(str(datetime.now()))
            symbols = ['TSLA', 'NIO', 'XPEV', 'LI',
                       'PYPL', 'AMZN', 'EBAY', 'ABNB', 'DKNG', 'DASH',
                       'FB', 'GOOG', 'ZM', 'AAPL', 'MSFT', 'UBER', 'LYFT', 'CRM', 'SNOW', 'VLDR',
                       'BABA', 'PDD', 'JD', 'TCEHY',
                       'BA', 'DAL', 'UAL', 'SPG', 'CCL', 'WMT', 'DIS', 'PFE', 'TDOC', 'PLUG', 'V',
                       'IVV', 'QQQ', 'IYW']

        #     symbols = ['PLUG']


            for symbol in symbols:
                driver.find_element_by_xpath("//input[@name = 'symbol']").click()
                driver.find_element_by_xpath("//input[@name = 'symbol']").clear()
                driver.find_element_by_xpath("//input[@name = 'symbol']").send_keys(symbol)
                driver.find_element_by_xpath("//input[@value = 'Go']").click()
                time.sleep(4)
                driver.find_element_by_xpath("//span[@class=\"export-menu-triangle\"]").click()
                driver.find_element_by_xpath("//div[@ng-click=\"clickExportSpreadsheet()\"]/..").click()

                time.sleep(5)

                list_of_files = glob.glob(r"C:\Users\yhfdidi\Downloads\Chart*.csv") # * means all if need specific format then *.csv
                latest_file = max(list_of_files, key=os.path.getctime)
                print(symbol + " record file: " + latest_file)

                df = pd.read_csv(latest_file)
                filt = [not pd.isnull(x) for x in df['Open']]
                df_need = df[filt].iloc[-5:]

                today = df_need.iloc[-1]
                if today['Close'] > today['BBUpper']:
                    msg = symbol + " 已突破上布林通道，考虑减仓"
                #     Thread(target = alert_popup, args = (msg))
                    print(msg)
                if today['Close'] < today['BBLower']:
                    msg = symbol + " 已跌破下布林通道，考虑加持"
                    print(msg)

                trend = (df_need['Close'].iloc[-1] - df_need['Close'].iloc[-3]) / df_need['Close'].iloc[-3]
                yesterday = df_need.iloc[-2]

                fom = ['SMA(20)', 'SMA(50)', 'SMA(150)']
                close  = 'Close'

                if trend > 0:
                    sign = "涨超"
                    if (today[close] - yesterday[close]) / yesterday[close] > 0.05:
                        print("今日," + symbol + "已经" + sign + " 5%")
                    for f in fom:
                        if today[close] > today[f] and yesterday[close] < today[f]:
                            print("今日," + symbol + "已经" + sign + f)

                else:
                    sign = "跌破"
                    if (-today[close] + yesterday[close]) / yesterday[close] > 0.05:
                        print("今日," + symbol + "已经" + sign + " 5%")
                    for f in fom:
                        if today[close] < today[f] and yesterday[close] > today[f]:
                            print("今日," + symbol + "已经" + sign + f)

            print('')                
            time.sleep(10)
            
run_main()

2021-01-07 13:41:02.540030
TSLA record file: C:\Users\yhfdidi\Downloads\Chart-20210107-134109.csv
TSLA 已突破上布林通道，考虑减仓
今日,TSLA已经涨超 5%
NIO record file: C:\Users\yhfdidi\Downloads\Chart-20210107-134119.csv
NIO 已突破上布林通道，考虑减仓
今日,NIO已经涨超 5%
XPEV record file: C:\Users\yhfdidi\Downloads\Chart-20210107-134128.csv
今日,XPEV已经涨超 5%
今日,XPEV已经涨超SMA(20)
今日,XPEV已经涨超SMA(50)
LI record file: C:\Users\yhfdidi\Downloads\Chart-20210107-134138.csv
LI 已突破上布林通道，考虑减仓
今日,LI已经涨超 5%
PYPL record file: C:\Users\yhfdidi\Downloads\Chart-20210107-134148.csv
今日,PYPL已经涨超SMA(20)
AMZN record file: C:\Users\yhfdidi\Downloads\Chart-20210107-134158.csv
EBAY record file: C:\Users\yhfdidi\Downloads\Chart-20210107-134208.csv
ABNB record file: C:\Users\yhfdidi\Downloads\Chart-20210107-134219.csv
今日,ABNB已经涨超 5%
DKNG record file: C:\Users\yhfdidi\Downloads\Chart-20210107-134229.csv
DASH record file: C:\Users\yhfdidi\Downloads\Chart-20210107-134239.csv
今日,DASH已经涨超 5%

In [22]:
pro1 = multiprocessing.Process(target = run_main)
pro1.start()
time.sleep(5)
pro1.terminate()

# Stock running module

In [27]:
# 目前需要手动设置到fidlity的买卖页面就绪
# 尚不清楚有什么隐私风险建议别放太多的钱到自动操作账户里面去...
handles = driver.window_handles
driver.switch_to.window(handles[1])

In [55]:
symbol = 'NIO'

driver.find_element_by_xpath("//input[@id = 'eq-ticket-dest-symbol']").clear()
driver.find_element_by_xpath("//input[@id = 'eq-ticket-dest-symbol']").send_keys(symbol)
driver.find_element_by_xpath("//input[@name = 'autofocus']").send_keys(u'\ue007') #"回车键"
time.sleep(3)
driver.find_element_by_xpath("//label[@for = 'action-buy']").click()
driver.find_element_by_xpath("//label[@for = 'quantity-type-shares']").click()
driver.find_element_by_xpath("//input[@id = 'eqt-shared-quantity']").clear()
driver.find_element_by_xpath("//input[@id = 'eqt-shared-quantity']").send_keys('1')
driver.find_element_by_xpath("//label[@for = 'market-yes']").click()
driver.find_element_by_xpath("//button[@id = 'previewOrderBtn']").click()
time.sleep(5)
driver.find_element_by_xpath("//button[@id = 'placeOrderBtn']").click()

KeyboardInterrupt:

# Playground

In [63]:
import matplotlib.pyplot as plt

In [67]:
df

,Date,Open,High,Low,Close,Volume,BBUpper,BBLower,SMA(20),SMA(50),SMA(150),"MACD(12,26)","EMA(9,Modern)",Histogram
0,01/04/2019,93.21,93.660,92.6900,93.44,8029144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01/07/2019,93.62,95.170,93.1800,94.54,7789701.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/08/2019,95.06,95.755,93.9100,95.20,7200912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01/09/2019,95.71,96.140,94.7700,94.89,6272293.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/10/2019,93.88,94.980,93.1201,94.96,9396271.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,12/28/2020,144.04,145.300,143.3300,145.22,6448325.0,152.555864,141.929136,147.2425,146.4232,136.326800,-0.915501,-0.415839,-0.499662
500,12/29/2020,145.64,145.845,143.5900,144.30,5979380.0,151.622971,142.013029,146.8180,146.4150,136.472267,-0.948352,-0.522342,-0.426011
501,12/30/2020,144.88,145.150,143.9400,144.18,6250385.0,150.516250,142.273750,146.3950,146.4396,136.608867,-0.972856,-0.612444,-0.360411
502,12/31/2020,144.20,144.270,142.8500,144.15,5938018.0,149.842640,142.310360,146.0765,146.4446,136.742800,-0.983360,-0.686627,-0.296733
503,01/04/2021,144.30,146.890,144.2800,146.53,10727414.0,149.412194,142.463806,145.9380,146.4872,136.893267,-0.790526,-0.707407,-0.083119

In [180]:
list_of_files = glob.glob(r"C:\Users\yhfdidi\Downloads\Chart*.csv")
for file in list_of_files:
#     file = r"C:\Users\yhfdidi\Downloads\Chart-20210104-180844.csv"
    df = pd.read_csv(file)
    filt = [not pd.isnull(x) for x in df['Open']]
    df = df[filt]
    res = 0
    stock = 0
    threshold = 0.0
    days_avg = 5
    for i in range(max(1,df.shape[0] - 90), df.shape[0]):
        if pd.isna(df.iloc[i-10]['Histogram']): continue
        hist_curr = df.iloc[i]['Histogram']
        hist_prev = df.iloc[i-1]['Histogram']
        if abs(hist_curr) > threshold:# and sum(df.iloc[i-days_avg:i+1]['Histogram'])/days_avg > 0:
            if hist_curr > 0 and hist_prev < 0 and not stock and df.iloc[i]['EMA(9,Modern)'] > -2:
                stock = 1
                buy = df.iloc[i]['Close']
#                 print(df.iloc[i]['Date'], 'Buy', df.iloc[i][['Close']].values)

            elif hist_curr < 0 and hist_prev > 0 and stock and df.iloc[i]['Close'] > buy: # and df.iloc[i]['EMA(9,Modern)'] < 0:
                stock = 0
                res += df.iloc[i]['Close'] - buy
#                 print(df.iloc[i]['Date'], 'Sell', df.iloc[i][['Close']].values)
#                 print(df.iloc[i]['Date'], "Revenue: ", df.iloc[i]['Close'] - buy)
    print(round(res/df['Close'].to_list()[-1] * 100,2),'%')

5.46 %
23.96 %
45.38 %
69.93 %
52.18 %
11.57 %
0.0 %
0.0 %
0.0 %
0.0 %
0.0 %
0.0 %
0.0 %
0.0 %
9.46 %
4.12 %
22.05 %
36.95 %
0.0 %
22.76 %
39.92 %
5.36 %
0.0 %
3.41 %
6.89 %
0.0 %
22.91 %
24.19 %
16.57 %
23.98 %
5.49 %
24.63 %
10.54 %
0.0 %
27.94 %
2.1 %
6.5 %
4.68 %
6.75 %
23.96 %
45.38 %
69.93 %
52.18 %
11.57 %
0.0 %
0.0 %
0.0 %
0.0 %
0.0 %
0.0 %
0.0 %
0.0 %
9.46 %
4.12 %
22.05 %
36.95 %
0.0 %
22.76 %
39.92 %
5.36 %

In [159]:
df.shape

(755, 14)

In [149]:
list_of_files = glob.glob(r"C:\Users\yhfdidi\Downloads\Chart*.csv")
list_of_files

['C:\\Users\\yhfdidi\\Downloads\\Chart-20210104-170533.csv',
 'C:\\Users\\yhfdidi\\Downloads\\Chart-20210104-170602.csv',
 'C:\\Users\\yhfdidi\\Downloads\\Chart-20210104-171354.csv',
 'C:\\Users\\yhfdidi\\Downloads\\Chart-20210104-180844.csv',
 'C:\\Users\\yhfdidi\\Downloads\\Chart-20210104-190142_wmt.csv']

In [81]:
# df.iloc[i]
df[['Close', 'Histogram']]

      Close  Histogram
0     93.44        NaN
1     94.54        NaN
2     95.20        NaN
3     94.89        NaN
4     94.96        NaN
..      ...        ...
499  145.22  -0.499662
500  144.30  -0.426011
501  144.18  -0.360411
502  144.15  -0.296733
503  146.53  -0.083119

[504 rows x 2 columns]

In [104]:
df.iloc[:,-1].fillna(0)
df

,Date,Open,High,Low,Close,Volume,BBUpper,BBLower,SMA(20),SMA(50),SMA(150),"MACD(12,26)","EMA(9,Modern)",Histogram
0,01/04/2019,93.21,93.660,92.6900,93.44,8029144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01/07/2019,93.62,95.170,93.1800,94.54,7789701.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/08/2019,95.06,95.755,93.9100,95.20,7200912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01/09/2019,95.71,96.140,94.7700,94.89,6272293.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/10/2019,93.88,94.980,93.1201,94.96,9396271.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,12/28/2020,144.04,145.300,143.3300,145.22,6448325.0,152.555864,141.929136,147.2425,146.4232,136.326800,-0.915501,-0.415839,-0.499662
500,12/29/2020,145.64,145.845,143.5900,144.30,5979380.0,151.622971,142.013029,146.8180,146.4150,136.472267,-0.948352,-0.522342,-0.426011
501,12/30/2020,144.88,145.150,143.9400,144.18,6250385.0,150.516250,142.273750,146.3950,146.4396,136.608867,-0.972856,-0.612444,-0.360411
502,12/31/2020,144.20,144.270,142.8500,144.15,5938018.0,149.842640,142.310360,146.0765,146.4446,136.742800,-0.983360,-0.686627,-0.296733
503,01/04/2021,144.30,146.890,144.2800,146.53,10727414.0,149.412194,142.463806,145.9380,146.4872,136.893267,-0.790526,-0.707407,-0.083119